version: '3.7'

services:
  tokenizer:
    image: mongo
    restart: always
    volumes:
      - ./tokenizer/db:/data/db # This is the location on your local machine where the entrails database documents will be stored
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    command: mongod --bind_ip_all
    ports:
      - "27017:27017"

  soc-faker-service:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      MONGO_INITDB_HOST: tokenizer
      MONGO_INITDB_DATABASE: tokenizer
      MONGO_INITDB_PORT: 27017
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MAIL_SERVER: smtp.googlemail.com
      MAIL_PORT: 587
      MAIL_USE_TLS: "True"
      MAIL_USERNAME: email@org.com
      MAIL_PASSWORD: super_secret_password
    ports:
      - "7001:7001"