version: '3.7'

services:
  swag:
    image: linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=2000
      - PGID=2000
      - TZ=America/Chicago
      - URL=soc-faker.com
      - VALIDATION=http
      - EMAIL= socfakerservice@gmail.com
      - STAGING=false #optional
    volumes:
      - ./data/nginx/site-confs/default:/config/nginx/site-confs/default
    ports:
      - 443:443
      - 80:80 #optional
    restart: unless-stopped

  tokenizer:
    image: mongo
    restart: always
    volumes:
      - ./tokenizer/db:/data/db # This is the location on your local machine where the entrails database documents will be stored
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    command: mongod --bind_ip_all
    expose:
      - 27017

  soc-faker-service:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      MONGO_INITDB_HOST: tokenizer
      MONGO_INITDB_DATABASE: tokenizer
      MONGO_INITDB_PORT: 27017
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MAIL_SERVER: smtp.googlemail.com
      MAIL_PORT: 587
      MAIL_USE_TLS: "True"
      MAIL_USERNAME: socfakerservice@gmail.com
      MAIL_PASSWORD: super_secret_password
    expose: 
      - 5000